name: "basic CI Pipeline"

on:
  push:
    branches:
     - main
     - test
  pull_request:
    branches:
     - main
    types:
     - opened
     - closed

# on:
#   push:
#     branches: [main]


jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "First step of push event"
        run: echo "On push event..."

  on-pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "First step of pull request"
        run: echo "On pull request event..."

  on-pull-request-opened:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: "First step of pull request opened"
        run: echo "On pull request event and opened action..."

  on-pull-request-closed:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: "First step of pull request closed"
        run: echo "On pull request event and closed action..."
