name: "Multi event workflow"

on:
  push:
    branches:
      - master
      - main

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      
      - name: "First step"
        run: ./script.sh          