name: "Multi event workflow"

on:
  push:
    branches:
      - master
      - main

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: "First step"
        run: sh ../../script.sh          