name: "Multi event workflow"

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
    types:
      - opened
      - closed  


jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"

      - name: "First step"
        run: ./script.sh 

  on-pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "on pull request"
        run: echo "Running on pull request"

  on-pull-request-opened:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: "on pull request opened"
        run: echo "Running on pull request open"

  on-pull-request-closed:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: "on pull request closed"
        run: echo "Running on pull request closed"
